<?php
define('ELATED_LISTING_VERSION', '1.1.4');
define('ELATED_LISTING_ABS_PATH', dirname(__FILE__));
define('ELATED_LISTING_REL_PATH', dirname(plugin_basename(__FILE__ )));
define('ELATED_LISTING_URL_PATH', plugin_dir_url( __FILE__ ));
define('ELATED_LISTING_ASSETS_PATH', ELATED_LISTING_ABS_PATH.'/assets');
define('ELATED_LISTING_ASSETS_URL_PATH', ELATED_LISTING_URL_PATH.'assets');
define('ELATED_LISTING_CPT_PATH', ELATED_LISTING_ABS_PATH.'/post-types');
define('ELATED_LISTING_CPT_URL_PATH', ELATED_LISTING_URL_PATH.'post-types');
define('ELATED_LISTING_SHORTCODES_PATH', ELATED_LISTING_ABS_PATH.'/shortcodes');
define('ELATED_LISTING_SHORTCODES_URL_PATH', ELATED_LISTING_URL_PATH.'shortcodes');